/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class by_bytechs_jni_JNIHelloWorld */

#ifndef _Included_by_bytechs_jni_JNIHelloWorld
#define _Included_by_bytechs_jni_JNIHelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     by_bytechs_jni_JNIHelloWorld
 * Method:    printHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_by_bytechs_jni_JNIHelloWorld_printHelloWorld
  (JNIEnv *, jobject);

/*
 * Class:     by_bytechs_jni_JNIHelloWorld
 * Method:    multiply
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_by_bytechs_jni_JNIHelloWorld_multiply
  (JNIEnv *, jobject, jint, jint);

JNIEXPORT jstring JNICALL Java_by_bytechs_jni_JNIHelloWorld_getLine
        (JNIEnv *env, jobject obj, jstring line);

#ifdef __cplusplus
}
#endif
#endif